# Generated by Django 3.2.2 on 2021-09-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0003_auto_20210926_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='stay',
            field=models.IntegerField(blank=True, max_length=256, null=True, verbose_name='long stay'),
        ),
    ]
