# Generated by Django 3.2.2 on 2021-09-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_nname'),
        ('stay', '0004_alter_stay_stay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='ipuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user ip'),
        ),
    ]
