# Generated by Django 3.2.2 on 2021-09-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0006_alter_stay_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='totprice',
            field=models.IntegerField(blank=True, null=True, verbose_name='total price'),
        ),
    ]
