# Generated by Django 3.2.2 on 2021-09-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0007_stay_totprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='totprice',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='total price'),
        ),
    ]
