# Generated by Django 3.2.2 on 2021-09-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_roomm_roday'),
        ('stay', '0010_alter_stay_totprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='brom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.roomm', verbose_name='room'),
        ),
    ]
