# Generated by Django 3.2.2 on 2021-09-27 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0012_alter_stay_brom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='username',
        ),
        migrations.AddField(
            model_name='stay',
            name='bookat',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='booked at'),
        ),
    ]
