# Generated by Django 3.2.2 on 2021-09-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0013_auto_20210927_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stay',
            options={'ordering': ('bookat',)},
        ),
    ]
