# Generated by Django 3.2.2 on 2021-09-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0014_alter_stay_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='sroprice',
            field=models.IntegerField(blank=True, null=True, verbose_name='rom price'),
        ),
    ]
