# Generated by Django 3.2.2 on 2021-09-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0016_stay_srooldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='srooldprice',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='previous rom price'),
        ),
        migrations.AlterField(
            model_name='stay',
            name='sroprice',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='rom price'),
        ),
    ]
