# Generated by Django 3.2.2 on 2021-07-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reimage', models.ImageField(blank='true', null='true', upload_to='images/')),
                ('rename', models.CharField(blank='true', max_length=10, null='true')),
                ('redes', models.TextField(blank='true', null='true')),
                ('rerate', models.IntegerField(blank='true', null='true')),
            ],
        ),
    ]
