# Generated by Django 3.2.2 on 2021-07-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rem',
            name='redes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rem',
            name='reimage',
            field=models.ImageField(upload_to='images/*'),
        ),
        migrations.AlterField(
            model_name='rem',
            name='rename',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rem',
            name='rerate',
            field=models.IntegerField(),
        ),
    ]
