# Generated by Django 3.2.2 on 2021-07-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210709_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rem',
            name='redes',
            field=models.TextField(verbose_name='your comment'),
        ),
        migrations.AlterField(
            model_name='rem',
            name='reimage',
            field=models.ImageField(upload_to='images/*', verbose_name='your photo'),
        ),
        migrations.AlterField(
            model_name='rem',
            name='rename',
            field=models.CharField(max_length=10, verbose_name='your name'),
        ),
        migrations.AlterField(
            model_name='rem',
            name='rerate',
            field=models.IntegerField(verbose_name='your rate'),
        ),
    ]
