# Generated by Django 3.2.2 on 2021-07-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210709_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rem',
            name='reimage',
            field=models.ImageField(upload_to='images', verbose_name='your photo'),
        ),
    ]
