# Generated by Django 3.2.2 on 2021-07-09 16:17

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_rem_reimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rem',
            name='reimage',
            field=models.ImageField(upload_to=reviews.models.reM.img, verbose_name='your photo'),
        ),
    ]
