# Generated by Django 3.2.2 on 2021-07-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_rem_reimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rem',
            options={'ordering': ['rerate']},
        ),
    ]
