# Generated by Django 3.2.2 on 2021-08-08 09:33

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roomM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roimage1', models.ImageField(blank='true', null='true', upload_to=home.models.roomM.roimage, verbose_name="rooms's image1")),
                ('roimage2', models.ImageField(blank='true', null='true', upload_to=home.models.roomM.roimage, verbose_name="rooms's image2")),
                ('roimage3', models.ImageField(blank='true', null='true', upload_to=home.models.roomM.roimage, verbose_name="rooms's image3")),
                ('roimage4', models.ImageField(blank='true', null='true', upload_to=home.models.roomM.roimage, verbose_name="rooms's image4")),
                ('roimage5', models.ImageField(blank='true', null='true', upload_to=home.models.roomM.roimage, verbose_name="rooms's image5")),
                ('roimage6', models.ImageField(blank='true', null='true', upload_to=home.models.roomM.roimage, verbose_name="rooms's image6")),
                ('roimage7', models.ImageField(blank='true', null='true', upload_to=home.models.roomM.roimage, verbose_name="rooms's image7")),
                ('roimage8', models.ImageField(blank='true', null='true', upload_to=home.models.roomM.roimage, verbose_name="rooms's image8")),
                ('roimage9', models.ImageField(blank='true', null='true', upload_to=home.models.roomM.roimage, verbose_name="rooms's image9")),
                ('roname', models.CharField(max_length=10, verbose_name="room's name")),
                ('rodes', models.TextField(verbose_name="room's description")),
                ('roprice', models.IntegerField(verbose_name="room's price")),
                ('roomoldprice', models.IntegerField(blank='true', null='true', verbose_name="room's previous price")),
                ('ronew', models.BooleanField(default=False, verbose_name='is new')),
                ('roavaliable', models.BooleanField(default=True, verbose_name='is avaliable')),
                ('ropostat', models.DateTimeField(auto_now=True, verbose_name='published at')),
                ('roslug', models.SlugField(blank='true', max_length=10, null='true')),
            ],
            options={
                'verbose_name': 'room',
                'db_table': 'room',
                'ordering': ['-roavaliable', '-ropostat'],
            },
        ),
        migrations.CreateModel(
            name='serviceM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogo', models.ImageField(blank='true', null='true', upload_to='services logos', verbose_name="logo's service")),
                ('stitle', models.CharField(max_length=10, verbose_name="title's service")),
                ('sdes', models.TextField(verbose_name='description of service')),
            ],
            options={
                'verbose_name': 'service',
                'db_table': 'service',
            },
        ),
    ]
