# Generated by Django 3.2.2 on 2021-08-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_roomm_roday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomm',
            name='roday',
        ),
    ]
