# Generated by Django 3.2.2 on 2021-08-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usname', models.CharField(max_length=50, verbose_name='name')),
                ('usbookfav', models.ManyToManyField(related_name='favouritroom', to='home.roomM', verbose_name='favourit rooms')),
                ('usrobook', models.ManyToManyField(related_name='bookroom', to='home.roomM', verbose_name='booked rooms')),
            ],
        ),
    ]
