# Generated by Django 3.2.2 on 2021-08-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usip',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='user ip'),
        ),
    ]
