# Generated by Django 3.2.2 on 2021-08-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_usip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usname',
        ),
    ]
