# Generated by Django 3.2.2 on 2021-08-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_usname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fer name'),
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='lser name'),
        ),
        migrations.AddField(
            model_name='user',
            name='usaddress',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='user name'),
        ),
        migrations.AddField(
            model_name='user',
            name='usphone',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone number'),
        ),
    ]
