# Generated by Django 3.2.2 on 2021-08-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210828_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='usname',
        ),
    ]
