# Generated by Django 3.2.2 on 2021-08-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_username_user_usname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fer name'),
        ),
    ]
