# Generated by Django 3.2.2 on 2021-09-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_nname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usaddress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usphone',
        ),
    ]
