# Generated by Django 3.2.2 on 2021-08-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orip', models.CharField(max_length=256, verbose_name='ip address')),
                ('orfname', models.CharField(max_length=256, verbose_name='first name')),
                ('orlname', models.CharField(max_length=256, verbose_name='last name')),
                ('ornname', models.CharField(max_length=256, verbose_name='nick name')),
                ('ordate', models.DateTimeField(auto_now=True, verbose_name='date booked')),
            ],
        ),
    ]
