# Generated by Django 3.2.2 on 2021-08-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orfname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orlname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ornname',
        ),
    ]
