# Generated by Django 3.2.2 on 2021-09-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0013_auto_20210927_1954'),
        ('order', '0002_auto_20210828_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stay.stay', verbose_name='booked details'),
        ),
        migrations.AddField(
            model_name='order',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='order',
            name='idnumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='id number'),
        ),
        migrations.AddField(
            model_name='order',
            name='ipuser',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='user ip'),
        ),
        migrations.AddField(
            model_name='order',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='order',
            name='mname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='middle name'),
        ),
        migrations.AddField(
            model_name='order',
            name='totprc',
            field=models.IntegerField(blank=True, null=True, verbose_name='total price'),
        ),
        migrations.AddField(
            model_name='order',
            name='usaddress',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='order',
            name='usphone',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone number'),
        ),
    ]
