# Generated by Django 3.2.2 on 2021-09-27 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210927_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('bookat',)},
        ),
        migrations.AddField(
            model_name='order',
            name='bookat',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='booked at'),
        ),
    ]
