# Generated by Django 3.2.2 on 2021-09-27 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210927_1954'),
        ('order', '0005_auto_20210927_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ipuser',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='user'),
        ),
    ]
