# Generated by Django 3.2.2 on 2021-09-27 21:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210927_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='usphone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
    ]
