# Generated by Django 3.2.2 on 2021-09-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_usphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='usaddress',
            new_name='usaddres',
        ),
    ]
