# Generated by Django 3.2.2 on 2021-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_usaddress_order_usaddres'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start booking in'),
        ),
    ]
